# .github/workflows/caller-workflow.yml
name: Build with Matrix Strategy
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "alpine1"
            context: "./alpine1"
            dockerfile_path: "./alpine1/Dockerfile"
            repository: "trial451ad8.jfrog.io/dev-docker-docker/alpine1"
            image_tag: "alpine1-${{ github.run_id }}"
            
          - name: "alpine2"
            context: "./alpine2"
            dockerfile_path: "./alpine2/Dockerfile"
            repository: "trial451ad8.jfrog.io/dev-docker-docker/alpine2"
            image_tag: "alpine2-${{ github.run_id }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Call reusable workflow
        uses: girichinna27/ortseam-worker/.github/workflows/reusable-workflow.yml@main
        with:
          image_name: ${{ matrix.name }} 
          context: ${{ matrix.context }}
          dockerfile_path: ${{ matrix.dockerfile_path }}  
          image_tag: ${{ matrix.image_tag }}
          registry: 'trial451ad8.jfrog.io'
          org: "ortseam"
          application_tags: "v1.0"
          artifacts: ${{ matrix.name }}
          artifactory_url: ${{ matrix.repository }}
        
        secrets:
          JFROG_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
