# .github/workflows/caller-workflow.yml
name: Build with Matrix Strategy
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: "alpine1"
            context: "./alpine1"
            dockerfile_path: "./alpine1/Dockerfile"
            repository: "trial451ad8.jfrog.io/dev-docker-docker/alpine1"
            image_tag: "alpine1-${{ github.run_id }}"
            
          - name: "alpine2"
            context: "./alpine2"
            dockerfile_path: "./alpine2/Dockerfile"
            repository: "trial451ad8.jfrog.io/dev-docker-docker/alpine2"
            image_tag: "alpine2-${{ github.run_id }}"

    uses: girichinna27/ortseam-worker/.github/workflows/reusable-workflow.yml@main
    with:
      image_name: ${{ matrix.name }} 
      context: ${{ matrix.context || '.' }}
      dockerfile: ${{ matrix.dockerfile_path || '' }}  # Fixed indentation
      image_tag: ${{ matrix.image_tag }}
      registry: 'trial451ad8.jfrog.io'
      org: "ortseam"
      application_tags: "v1.0"
      artifacts: ${{ matrix.name }}
      artifactory_url: ${{ matrix.repository }}

    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
